# Generated by Django 5.0.3 on 2024-04-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Nome da Avaliação'),
        ),
    ]
